version: '3.1'

services:

  php_fpm:
    image: boxbilling:1.4
    container_name: bb-fpm
    restart: unless-stopped
    volumes:
      - ./docker/php/php.ini-production:/usr/local/etc/php/conf.d/php.ini
      - ./public:/var/www/html
    depends_on:
      - mysql
    networks:
      - bb-network

  nginx:
    image: nginx:alpine
    container_name: bb-nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx1.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html
    depends_on:
      - php_fpm
      - mysql
    ports:
      - "8004:80"
    networks:
      - bb-network

  mysql:
    image: mysql:5.7.22
    # image: mariadb:10.1.38
    container_name: bb-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: boxbilling
      MYSQL_USER: user_bb
      MYSQL_PASSWORD: pass_bb
      MYSQL_ROOT_PASSWORD: azzam
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - bb-network

  ftp:
    image: atmoz/sftp:latest
    container_name: bb-ftp
    networks:
      - bb-network
    ports:
      - "2112:22"
    command: userboxbilling:4zz4maziz1
    volumes:
      - ./public:/home/userboxbilling/public_html
    restart: always

networks:
  bb-network:

volumes:
  mysql:
    driver: local
