version: '3.6'

services: 
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: azzam
            MYSQL_DATABASE: boxbilling_import
            MYSQL_USER: user_bb
            MYSQL_PASSWORD: pass_bb
    
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
        networks:
            - bb-seeder

    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080
networks:
  bb-seeder: