version: '3.1'

services:

  php_fpm:
    image: niagahoster/frontend:1.1
    container_name: app_frontend
    networks:
      - front-network
    restart: unless-stopped
    volumes:
      - ./docker/php/php.ini-production:/usr/local/etc/php/conf.d/php.ini
      - ./app:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx_frontend
    networks:
      - front-network
    depends_on:
      - php_fpm
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx1.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html

  mysql:
    image: mysql:5.7.22
    # image: mariadb:10.1.38
    container_name: db_frontend
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: niagahoster
      MYSQL_ROOT_PASSWORD: azzam
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - front-network

networks:
  front-network:
